// <auto-generated />
namespace SearchGoogleAPIone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Fourth : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fourth));
        
        string IMigrationMetadata.Id
        {
            get { return "201802011105488_Fourth"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
