namespace SearchGoogleAPIone.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class Second : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.RootObjects", "context_title", "dbo.Contexts");
            DropForeignKey("dbo.Items", "RootObject_kind", "dbo.RootObjects");
            DropForeignKey("dbo.RootObjects", "searchInformation_searchTime", "dbo.SearchInformations");
            DropForeignKey("dbo.RootObjects", "url_type", "dbo.Urls");
            DropIndex("dbo.Items", new[] { "RootObject_kind" });
            DropIndex("dbo.RootObjects", new[] { "context_title" });
            DropIndex("dbo.RootObjects", new[] { "searchInformation_searchTime" });
            DropIndex("dbo.RootObjects", new[] { "url_type" });
            RenameColumn(table: "dbo.RootObjects", name: "context_title", newName: "context_Id");
            RenameColumn(table: "dbo.Items", name: "RootObject_kind", newName: "RootObject_Id");
            RenameColumn(table: "dbo.RootObjects", name: "searchInformation_searchTime", newName: "searchInformation_Id");
            RenameColumn(table: "dbo.RootObjects", name: "url_type", newName: "url_Id");
            DropPrimaryKey("dbo.Aggregateratings");
            DropPrimaryKey("dbo.Contexts");
            DropPrimaryKey("dbo.CseImages");
            DropPrimaryKey("dbo.CseThumbnails");
            DropPrimaryKey("dbo.Hcards");
            DropPrimaryKey("dbo.Itemlists");
            DropPrimaryKey("dbo.Items");
            DropPrimaryKey("dbo.Metatags");
            DropPrimaryKey("dbo.Mobileapplications");
            DropPrimaryKey("dbo.Offers");
            DropPrimaryKey("dbo.Organizations");
            DropPrimaryKey("dbo.People");
            DropPrimaryKey("dbo.Webpages");
            DropPrimaryKey("dbo.NextPages");
            DropPrimaryKey("dbo.Requests");
            DropPrimaryKey("dbo.RootObjects");
            DropPrimaryKey("dbo.SearchInformations");
            DropPrimaryKey("dbo.Urls");
            AddColumn("dbo.Aggregateratings", "Id", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.Contexts", "Id", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.CseImages", "Id", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.CseThumbnails", "Id", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.Hcards", "Id", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.Itemlists", "Id", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.Items", "Id", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.Metatags", "Id", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.Mobileapplications", "Id", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.Offers", "Id", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.Organizations", "Id", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.People", "Id", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.Webpages", "Id", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.NextPages", "Id", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.Requests", "Id", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.RootObjects", "Id", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.SearchInformations", "Id", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.Urls", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Aggregateratings", "ratingvalue", c => c.String());
            AlterColumn("dbo.Contexts", "title", c => c.String());
            AlterColumn("dbo.CseImages", "src", c => c.String());
            AlterColumn("dbo.CseThumbnails", "width", c => c.String());
            AlterColumn("dbo.Hcards", "fn", c => c.String());
            AlterColumn("dbo.Itemlists", "itemlistelement", c => c.String());
            AlterColumn("dbo.Items", "kind", c => c.String());
            AlterColumn("dbo.Items", "RootObject_Id", c => c.Int());
            AlterColumn("dbo.Metatags", "Title", c => c.String());
            AlterColumn("dbo.Mobileapplications", "url", c => c.String());
            AlterColumn("dbo.Offers", "url", c => c.String());
            AlterColumn("dbo.Organizations", "url", c => c.String());
            AlterColumn("dbo.People", "org", c => c.String());
            AlterColumn("dbo.Webpages", "name", c => c.String());
            AlterColumn("dbo.NextPages", "title", c => c.String());
            AlterColumn("dbo.Requests", "title", c => c.String());
            AlterColumn("dbo.RootObjects", "kind", c => c.String());
            AlterColumn("dbo.RootObjects", "context_Id", c => c.Int());
            AlterColumn("dbo.RootObjects", "searchInformation_Id", c => c.Int());
            AlterColumn("dbo.RootObjects", "url_Id", c => c.Int());
            AlterColumn("dbo.Urls", "type", c => c.String());
            AddPrimaryKey("dbo.Aggregateratings", "Id");
            AddPrimaryKey("dbo.Contexts", "Id");
            AddPrimaryKey("dbo.CseImages", "Id");
            AddPrimaryKey("dbo.CseThumbnails", "Id");
            AddPrimaryKey("dbo.Hcards", "Id");
            AddPrimaryKey("dbo.Itemlists", "Id");
            AddPrimaryKey("dbo.Items", "Id");
            AddPrimaryKey("dbo.Metatags", "Id");
            AddPrimaryKey("dbo.Mobileapplications", "Id");
            AddPrimaryKey("dbo.Offers", "Id");
            AddPrimaryKey("dbo.Organizations", "Id");
            AddPrimaryKey("dbo.People", "Id");
            AddPrimaryKey("dbo.Webpages", "Id");
            AddPrimaryKey("dbo.NextPages", "Id");
            AddPrimaryKey("dbo.Requests", "Id");
            AddPrimaryKey("dbo.RootObjects", "Id");
            AddPrimaryKey("dbo.SearchInformations", "Id");
            AddPrimaryKey("dbo.Urls", "Id");
            CreateIndex("dbo.Items", "RootObject_Id");
            CreateIndex("dbo.RootObjects", "context_Id");
            CreateIndex("dbo.RootObjects", "searchInformation_Id");
            CreateIndex("dbo.RootObjects", "url_Id");
            AddForeignKey("dbo.RootObjects", "context_Id", "dbo.Contexts", "Id");
            AddForeignKey("dbo.Items", "RootObject_Id", "dbo.RootObjects", "Id");
            AddForeignKey("dbo.RootObjects", "searchInformation_Id", "dbo.SearchInformations", "Id");
            AddForeignKey("dbo.RootObjects", "url_Id", "dbo.Urls", "Id");
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.RootObjects", "url_Id", "dbo.Urls");
            DropForeignKey("dbo.RootObjects", "searchInformation_Id", "dbo.SearchInformations");
            DropForeignKey("dbo.Items", "RootObject_Id", "dbo.RootObjects");
            DropForeignKey("dbo.RootObjects", "context_Id", "dbo.Contexts");
            DropIndex("dbo.RootObjects", new[] { "url_Id" });
            DropIndex("dbo.RootObjects", new[] { "searchInformation_Id" });
            DropIndex("dbo.RootObjects", new[] { "context_Id" });
            DropIndex("dbo.Items", new[] { "RootObject_Id" });
            DropPrimaryKey("dbo.Urls");
            DropPrimaryKey("dbo.SearchInformations");
            DropPrimaryKey("dbo.RootObjects");
            DropPrimaryKey("dbo.Requests");
            DropPrimaryKey("dbo.NextPages");
            DropPrimaryKey("dbo.Webpages");
            DropPrimaryKey("dbo.People");
            DropPrimaryKey("dbo.Organizations");
            DropPrimaryKey("dbo.Offers");
            DropPrimaryKey("dbo.Mobileapplications");
            DropPrimaryKey("dbo.Metatags");
            DropPrimaryKey("dbo.Items");
            DropPrimaryKey("dbo.Itemlists");
            DropPrimaryKey("dbo.Hcards");
            DropPrimaryKey("dbo.CseThumbnails");
            DropPrimaryKey("dbo.CseImages");
            DropPrimaryKey("dbo.Contexts");
            DropPrimaryKey("dbo.Aggregateratings");
            AlterColumn("dbo.Urls", "type", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.RootObjects", "url_Id", c => c.String(maxLength: 128));
            AlterColumn("dbo.RootObjects", "searchInformation_Id", c => c.Double());
            AlterColumn("dbo.RootObjects", "context_Id", c => c.String(maxLength: 128));
            AlterColumn("dbo.RootObjects", "kind", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Requests", "title", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.NextPages", "title", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Webpages", "name", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.People", "org", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Organizations", "url", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Offers", "url", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Mobileapplications", "url", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Metatags", "Title", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Items", "RootObject_Id", c => c.String(maxLength: 128));
            AlterColumn("dbo.Items", "kind", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Itemlists", "itemlistelement", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Hcards", "fn", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.CseThumbnails", "width", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.CseImages", "src", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Contexts", "title", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Aggregateratings", "ratingvalue", c => c.String(nullable: false, maxLength: 128));
            DropColumn("dbo.Urls", "Id");
            DropColumn("dbo.SearchInformations", "Id");
            DropColumn("dbo.RootObjects", "Id");
            DropColumn("dbo.Requests", "Id");
            DropColumn("dbo.NextPages", "Id");
            DropColumn("dbo.Webpages", "Id");
            DropColumn("dbo.People", "Id");
            DropColumn("dbo.Organizations", "Id");
            DropColumn("dbo.Offers", "Id");
            DropColumn("dbo.Mobileapplications", "Id");
            DropColumn("dbo.Metatags", "Id");
            DropColumn("dbo.Items", "Id");
            DropColumn("dbo.Itemlists", "Id");
            DropColumn("dbo.Hcards", "Id");
            DropColumn("dbo.CseThumbnails", "Id");
            DropColumn("dbo.CseImages", "Id");
            DropColumn("dbo.Contexts", "Id");
            DropColumn("dbo.Aggregateratings", "Id");
            AddPrimaryKey("dbo.Urls", "type");
            AddPrimaryKey("dbo.SearchInformations", "searchTime");
            AddPrimaryKey("dbo.RootObjects", "kind");
            AddPrimaryKey("dbo.Requests", "title");
            AddPrimaryKey("dbo.NextPages", "title");
            AddPrimaryKey("dbo.Webpages", "name");
            AddPrimaryKey("dbo.People", "org");
            AddPrimaryKey("dbo.Organizations", "url");
            AddPrimaryKey("dbo.Offers", "url");
            AddPrimaryKey("dbo.Mobileapplications", "url");
            AddPrimaryKey("dbo.Metatags", "Title");
            AddPrimaryKey("dbo.Items", "kind");
            AddPrimaryKey("dbo.Itemlists", "itemlistelement");
            AddPrimaryKey("dbo.Hcards", "fn");
            AddPrimaryKey("dbo.CseThumbnails", "width");
            AddPrimaryKey("dbo.CseImages", "src");
            AddPrimaryKey("dbo.Contexts", "title");
            AddPrimaryKey("dbo.Aggregateratings", "ratingvalue");
            RenameColumn(table: "dbo.RootObjects", name: "url_Id", newName: "url_type");
            RenameColumn(table: "dbo.RootObjects", name: "searchInformation_Id", newName: "searchInformation_searchTime");
            RenameColumn(table: "dbo.Items", name: "RootObject_Id", newName: "RootObject_kind");
            RenameColumn(table: "dbo.RootObjects", name: "context_Id", newName: "context_title");
            CreateIndex("dbo.RootObjects", "url_type");
            CreateIndex("dbo.RootObjects", "searchInformation_searchTime");
            CreateIndex("dbo.RootObjects", "context_title");
            CreateIndex("dbo.Items", "RootObject_kind");
            AddForeignKey("dbo.RootObjects", "url_type", "dbo.Urls", "type");
            AddForeignKey("dbo.RootObjects", "searchInformation_searchTime", "dbo.SearchInformations", "searchTime");
            AddForeignKey("dbo.Items", "RootObject_kind", "dbo.RootObjects", "kind");
            AddForeignKey("dbo.RootObjects", "context_title", "dbo.Contexts", "title");
        }
    }
}
